### PR TITLE
Add simple code line For single-GPU users.

### PR DESCRIPTION
**Pull request by Zero-coder**
Thanks.

### CODE REVIEW

**Comment by ts-kim** [comment]
Hi, thank you for your attention to our work.

I was wondering, why do we need to include .to(device) as you suggested? 
Since the RevIN class inherits from nn.Module, using model.to(device) in the training code will also modify the device of RevIN accordingly.

**Comment by Zero-coder** [comment]
> 

Yes, you are right, my mistake for making this not complete, I have added two line code to interpret this thoroughly.

**Comment by Zero-coder** [comment]
I will start a new pull request depends on owner's willing.

**Comment by ts-kim** [comment]
Okay, I will close this pull request. 
If you have more questions, please create them as a GitHub issue.

**Comment by Zero-coder** [comment]
Never mind it, I just want to make convinience for the readers.

**Pull request closed without merging**
